---
- name: "create dir"
  become: true
  file:
    path: ~/backend
    state: directory

- name: "copy files"
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/backend

- name: "install npm"
  become: true
  apt:
    name: npm
    state: latest
    update_cache: true

- name: "install"
  shell: |
    cd ~/backend
    npm install

- name: "setup"
  shell: |
    cd ~/backend
    pm2 stop default

- name: "start app"
  shell: |
    cd ~/backend
    pm2 start npm -- start