---
- name: "create dir"
  become: true
  file:
    path: ~/backend
    state: directory

- name: "copy files"
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu

- name: "install npm"
  become: true
  apt:
    name: npm
    state: latest
    update_cache: true
  
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    state: present

- name: "install"
  become: true
  shell: |
    npm install

- name: "start app"
  become: true
  shell: |
    pm2 start npm -- start